### PR TITLE
Fix Screen size problem

### LINKED ISSUE #4: screen size problem
This activity was tested on Ubuntu 16.04 sucrose with a 1024x768 screen. The activity apparently assumes a 1200x900 screen. As a result important information is invisible making it unusable.

### PR DESCRIPTION
**Pull request by nswarup14**
Fixes #4 
**Changes**
```
1) .gitignore
2) LemonadeMain.py
3) activity.py
4) activity/activity.info
5) fortuneengine/GameEngine.py
6) setup.py
7) po/Lemonade.pot 
```

**Updates**
1) Fixed `setup.py` and its corresponding commands and generated `po/` files.
2) Tried to fix the screen resolution issue as pointed out by @tony37

**Issues**
1) I'm actually not sure if the screen resolution problem is fixed completely. Even after numerous testing, I'm not convinced as there is still some information left out from the screen. What I have attempted is feed in the screen's size by getting it through the `pygame` library, rather than keep it fixed and static (i.e 1200x900). I like to welcome others to test it on their respective development environments to see what has changed. I can perhaps improve the PR after seeing it tested on other PC's. 

Thanks

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  I've tested on an Ubuntu 18.04 VM with 1024x768 screen, but the instructions are not visible.

**Comment by quozl** [comment]
Fixes https://github.com/sugarlabs/Lemonade/pull/9

**Comment by Aniket21mathur** [comment]
As @nswarup14  is fixing #8  in this pull request I think  we should close #9.Thanks!

**Comment by quozl** [comment]
Thanks for the suggestion.  I see no reason to close the other pull request; both solve certain problems and I can't be sure which pull request will merge first, as it depends on how available people are.  There is no rush.  I'm waiting for an answer to 1024x768 screen instructions not visible.

**Comment by Aniket21mathur** [comment]
@nswarup14  are you still working on this?
Thanks!

**Comment by nswarup14** [comment]
@Aniket21mathur 
No, I'm not working on this currently. Sorry for replying sooner.
Thanks

**Pull request closed without merging**
